CREATE TABLE traffic_data (
    count_point_id INT,
    direction_of_travel TEXT,
    year INT,
    count_date DATE,
    hour INT,
    region_id INT,
    region_name TEXT,
    local_authority_id INT,
    local_authority_name TEXT,
    road_name TEXT,
    road_type TEXT,
    start_junction_road_name TEXT,
    end_junction_road_name TEXT,
    easting DOUBLE,
    northing DOUBLE,
    latitude DOUBLE,
    longitude DOUBLE,
    link_length_km DOUBLE,
    link_length_miles DOUBLE,
    pedal_cycles INT,
    two_wheeled_motor_vehicles INT,
    cars_and_taxis INT,
    buses_and_coaches INT,
    lgvs INT,
    hgvs_2_rigid_axle INT,
    hgvs_3_rigid_axle INT,
    hgvs_4_or_more_rigid_axle INT,
    hgvs_3_or_4_articulated_axle INT,
    hgvs_5_articulated_axle INT,
    hgvs_6_articulated_axle INT,
    all_hgvs INT,
    all_motor_vehicles INT,
    PRIMARY KEY (count_point_id, count_date)
);
